### ISSUE TITLE
Build docker image from bosh stemcells

### ISSUE THREAD

**Issue by zhanggbj** [SUSE/fissile#253]
Hi,

I want to build a docker image from bosh stemcells following [guide](https://github.com/SUSE/fissile/blob/master/docs/stemcells.md).  Since I can't access the [pipeline](https://ci.from-the.cloud/teams/main/login?redirect=%2Fteams%2Fmain%2Fpipelines%2Fbosh-os-images), I'm not sure what the bosh stemcell stages are included to build the image. Would you please help provide the detailed stage list?

Thanks a lot!

**Comment by mook-as** [comment]
Hi there!
Sorry about that.  The _sources_ of the pipeline is available at [SUSE/bosh-linux-stemcell-builder-ci]; the [openSUSE stemcell sources] and [Ubuntu stemcell sources] are also public.  Hopefully that's enough information to help you get started; please do ask if you need more specifics.

Keeping this open since it means we need to write more and better docs.

[SUSE/bosh-linux-stemcell-builder-ci]: https://github.com/SUSE/bosh-linux-stemcell-builder-ci
[openSUSE stemcell sources]: https://github.com/SUSE/fissile-stemcell-openSUSE
[Ubuntu stemcell sources]: https://github.com/cloudfoundry-community/fissile-stemcell-ubuntu

**Comment by zhanggbj** [comment]
@mook-as Thank you for your reply, I've found what I need in the sources of the pipeline you provided.
