### ISSUE TITLE
Where is the dockerfile?

### ISSUE THREAD

**Issue by qibobo** [SUSE/fissile#312]
I use fissile build images successfully. In the work dir there is a dockerfiles directory, but no dockerfile in it. How to find the docker files?

**Comment by mook-as** [comment]
In general, the docker files don't actually exist (they are created and passed to docker directory in a tar file that never hits disk). If you want to inspect things, try [`fissile build images --output-directory`](https://github.com/SUSE/fissile/blob/master/docs/generated/fissile_build_images.md), which will cause the tar file to be written to disk instead, and the docker image will not be built (but you can then do so using the tar file created).

(Slack is probably a better place for questions, rather than issues. We're just monitoring both anyway, so it's not like you'd get a faster response this way.)

**Comment by giner** [comment]
The documentation doesn't mention the Slack channel. How to find it? @mook-as

**Comment by jandubois** [comment]
@giner The closest channel for fissile would be #quarks-dev on https://cloudfoundry.slack.com
