### ISSUE TITLE
Container start error

### ISSUE THREAD

**Issue by qibobo** [SUSE/fissile#313]
Every container failed with the same error msg as below: What is the problem?

/usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/lib/generate.rb:24:in `rescue in generate': failed to read template file /opt/fissile/monitrc.erb (RuntimeError)
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/lib/generate.rb:19:in `generate'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/bin/configgin:34:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/bin/configgin:23:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/bin/configgin:23:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/bin/configgin:20:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.12.0.pre/bin/configgin:20:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/configgin:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/configgin:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by mook-as** [comment]
I think that means you're using an older stemcell; we recently cleaned things up a bit and moved `/opt/hcf` to `/opt/fissile` (because HCF isn't actually a thing anymore, and doesn't make sense in fissile context anyway since in theory fissile isn't tied to _our_ distribution), and your stemcell was probably a bit older and didn't have that change.

Sorry about that; we should have poked people in #fissile more; I'll discuss this with others to try to mitigate this in the future.

**Comment by qibobo** [comment]
@mook-as thank you. stemcell version error.
